### ISSUE TITLE
Replace `aws` cli with boto3

### ISSUE THREAD

**Issue by giorgiosironi** [gmaciocci/eLifeDigestToMP3#2]
The Python SDK for AWS gives much more control over using an external process, as it checks for errors and returns an output that can be printed:
https://boto3.readthedocs.io/en/latest/reference/services/polly.html

It can also be required to be a particular version, as my `aws` utility was too old and couldn't accept the `polly` command, failing silently.

**Comment by gmaciocci** [comment]
Done, thank you.
