### ISSUE TITLE
temp.xml prevents multiple instances from running concurrently

### ISSUE THREAD

**Issue by giorgiosironi** [gmaciocci/eLifeDigestToMP3#4]
More than one process would clash on the temporary file https://github.com/gmaciocci/eLifeDigestToMP3/blob/dcb4c201f36d6c340f4a10e9bccd7228c7ce3d50/DigestBot2.py#L70-L71 
A [unique filename](https://stackoverflow.com/a/2961629/91590) could be used in its place.

**Comment by gmaciocci** [comment]
Resolved, thank you
