### ISSUE TITLE
Python 3 compatibility 

### ISSUE THREAD

**Issue by seanwiseman** [gmaciocci/eLifeDigestToMP3#5]
A few things in `DigestBot2.py` will prevent this from being run with Python 3:

For example:
https://github.com/gmaciocci/eLifeDigestToMP3/blob/dcb4c201f36d6c340f4a10e9bccd7228c7ce3d50/DigestBot2.py#L80

This is the Python 2 only style of `print` statement.

I would be happy to put a PR together for this if you would like me to.

**Comment by gmaciocci** [comment]
That would be great, thank you. Note the latest working prototype has been named DigestBot3.py

**Comment by gmaciocci** [comment]
The script is now tested and working with Python 3.
